dist: trusty
sudo: required
group: beta
language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
env:
  secure: RymZPAUgaq7nxQsu4Cj0GmEyQ/KlLfvB8hoMzK94l+t+0yrUPe1bA/nGGCYD1KOJeG8mHbSg3QdQ+RC+xaV5TOGDSP2CNCUewgwrqVcWKsXzZFmqk1qEvwI5m30oY8C/0VQEg9KnxvDU7STvGFBh4hCRMWWib/GI0rnK3vbGognd+4AZGKCpzVwluGADnt9g125iWoljGoD26Gf9EaiGpGe1shUEPDnMe1vw69nD7TB/2lcFdyDH7wzeswKPmlv9LGxG9AFh11IuNkAtmtRUqSqrh72e1JHe+zB4/DQc34wiZcOp81J8bwFbtLGY63cfG6qBgt3im1dEpCnz7ZOyiNE+DkNI8QqsCfC/ic1yP0ka718oMcM4dpc/KgW9Nt88n98lCwwQMBdWhPtZdf2QnDtIb+S2SSS4WIRjjTA1VHWqlD7wzaLQvScJQV0wNoTlbkfFstzh1RF5BS7a/OMTIPZKGNOnYdtsDm2DgQmRBaYmJjYLsHaHYxpPWjX71VT7g7FsLH0x9DGkTjEKm8VyXR1HqU1XNka0wdqEkSPCHgkXBqHRKYlUiE+nwexyHeubopRhdButdIkjV9RHPiiRK7mIjLqXT6+KoCVRSk5Y410yZDe9xmus3cIkPgfh5PxsqkXTXjXilXXP75CQlk8JwFi3BRzAAU0thjgcz8tGYO8=
jobs:
  include:
  - stage: tests
    script:
    - npm run start-ganache &
    - npm run test
  - stage: Deploy and publish
    script:
    - "./scripts/pullContracts.sh"
    - "./scripts/migrate.sh rinkeby"
    - "./scripts/migrate.sh kovan"
    deploy:
      provider: npm
      skip_cleanup: true
      email: razvan@centrifuge.io
      api_key:
        secure: jvnLUutoMYXcgWT8qq3ZN2xX7x4633HKCzeU+W3ZFRkFDhyilAuWiwP80IiYo1DZcd8Fz7iJLTmDItPn9ymETj4nglWk4AARMaCpfM3wISkQG535MPQejAQ2qDfDFA85ffZHaTbSXM7Z/TdvCmRi4LIS3JDh9NtxsKjNzybgXVduuZVdpGiLR6zY+vy7wBZWGIc0T4bevgAq7CGaHLZJS2MNY+MT7l/QecsP2PKA6g3UoBhoe+S6UxfTgoc9qU938Nc5Vg/wz4VoKINdf8XlJhR5sAlzWItW0Jp1OrzivB/FdmEZBLVknaK+dS3TPtWI5mQ3Ly96NlTk++WtzORsfPa6jgWOA9G/BwnCVrR4YNQomzOD1CV7eoO/8Fd1hVRkXyXlncR341uaApLcJcSgUOldm/btG0kBgfD1So3K+69w33tBIgzy1tv7pMFzBTG/377u9/9+5J9ezLJ8F5BSNh+EYI6JGpGikNuo0wv1Nb8RM9xBXNcVA3fic3pVPTjozdpIW3YkZT/nQNjIbsHcXNJAMRgLp2zJMAIXTqBmZMocrRQDH/7zkgl8CcWgkOZSgrlU/Q7nXqLyF8RoAIclj/Jhk5KwW7w1G/LWzwkF3W9rV+c86TEwQezI+BlPJaPICFENXY50x3zlM+PB1DgBb8zsr4teXmRfKqrvkdwy+gc=
      on:
        repo: centrifuge/centrifuge-ethereum-contracts
        branch: fix-travis-deploy
