dist: trusty
sudo: required
group: beta
language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
env:
  secure: RymZPAUgaq7nxQsu4Cj0GmEyQ/KlLfvB8hoMzK94l+t+0yrUPe1bA/nGGCYD1KOJeG8mHbSg3QdQ+RC+xaV5TOGDSP2CNCUewgwrqVcWKsXzZFmqk1qEvwI5m30oY8C/0VQEg9KnxvDU7STvGFBh4hCRMWWib/GI0rnK3vbGognd+4AZGKCpzVwluGADnt9g125iWoljGoD26Gf9EaiGpGe1shUEPDnMe1vw69nD7TB/2lcFdyDH7wzeswKPmlv9LGxG9AFh11IuNkAtmtRUqSqrh72e1JHe+zB4/DQc34wiZcOp81J8bwFbtLGY63cfG6qBgt3im1dEpCnz7ZOyiNE+DkNI8QqsCfC/ic1yP0ka718oMcM4dpc/KgW9Nt88n98lCwwQMBdWhPtZdf2QnDtIb+S2SSS4WIRjjTA1VHWqlD7wzaLQvScJQV0wNoTlbkfFstzh1RF5BS7a/OMTIPZKGNOnYdtsDm2DgQmRBaYmJjYLsHaHYxpPWjX71VT7g7FsLH0x9DGkTjEKm8VyXR1HqU1XNka0wdqEkSPCHgkXBqHRKYlUiE+nwexyHeubopRhdButdIkjV9RHPiiRK7mIjLqXT6+KoCVRSk5Y410yZDe9xmus3cIkPgfh5PxsqkXTXjXilXXP75CQlk8JwFi3BRzAAU0thjgcz8tGYO8=
jobs:
  include:
  - stage: tests
    script:
    - npm run start-ganache &
    - npm run test

    deploy:
      provider: npm
      skip_cleanup: true
      email: razvan@centrifuge.io
      api_key:
        secure: kNNwW655RKvE6cdv9jjxBYqsc9KsZoLB2ZgUIbp+KDep7jNbbBhjPtzwUVuIK8n2qL57iLzgZSRKSQVLQfOLmEGVAVDm4E/3TM6ysB32O/1gKYTuuD/kM9xuo9Z/m2rMSQPLxfqnk1mmKXnbh4us6qbUPfHHlD0irZXq4rBWdCLOU5lpyxWA/dTU4OhRfiCrQj57L7VpRq9M03JLBTPTBGQUgk53/cDF1OY8nHMaPcJc7uU0iaGtNNqt8+aF59O6OO2bFTRu9hHfkStB1SZ3kOqnjADKqTTTIGCjCE3LGCzXAIkqwy4JMw74VxC+8e9A6yMVcCWtbAwou94cIdLGZkmj2FDY+BNwYYuuwH42fp32JdVZY+/PYhdukjMHJWZkw1gMZCtkOZUR0VNsJv0l9XpfAttzCeZIVS9G6gZI0h2UN3HBoP7nAonv+c/iRG0MlSLFss/Wm38wQpeJSrXVHq58UMR+kPA9V06Xca7wCPC+QCRTyrDr5sDSsN/G9YkuCN+SJM42wrDmto0fk3O4G1c8wxnPmqVgZPQBVD9SOsbgEcgB8jHKMtySVdOlS63sNe12V4hacMXllKJuVx5sfZ0h039lJnwHUro4mBKWKpJKnM4oWmnkg+44GaVbtsDQ30QRsldCN0sZ0kjLAf3QXCnaXGBVcf1ZLs0Fxw6MFCM=
      on:
        repo: centrifuge/centrifuge-ethereum-contracts
        branch: fix-travis-deploy
