dist: trusty
sudo: required
group: beta
language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules

script:
 - npm run start-ganache &
 - npm run test

env:
  secure: QScayrjushGujxRDsfmYwmm031RVR5BFPWyMK03CXnh/SZrumLVsDbBcab0z46ETTpMPOKX13kl3XRW17tpVYQ0EbOZyExfxSbRWf+Kkri4hjnEv1XewIcaMKs3uKeeZNahWiDRm9buLNjgvNgGC1t2BQntFjvt3LM5biWvTyeFeFzb1mEip4nRHNmKYdc5kg01bUJPG9UpKRC1AhsaQL06s/QoSQwneAlNG9t0t9ErTOLdbz1Vs0I5WEMVVzASigOSt7efQBqg3oDRZTmbCkGxQRxMr5PextmMeeWyY8PhufMP7BKtX/W28GOKFzsJtniOdKt795MQwrm/kCQPCT4+l1o3REz4noCQwBdl69t15ksoM6HDzSyCLhz2l3cEpHsSet+QF6TqCGmDP4fBtZkPhJTVedW9tVHb3RI65AxtWsZVK9+AjAsOOZlcGjvVNuzJlem2PPAGRayQ2FC4WNehlWyjg55HgFs7sHdMI5LwbpTXTRq34IF6XdtNUZx0XrpmjVpSskGwZvVsuizbNjrsRlUpVJwgCgLmiVDYpZOb0N1uWULXGQy0HjugTPg63mWHmcnHGdcCd1kWadavP7Fd3Stg79Hqlw8NFEQdtc8Zqqhra2miN+bU1VwUyiBSBuoTcaa/eERguxtk68RhHBxFRNW+ogLHi1bKOTFuRQbM=

jobs:
  include:
  - stage: tests
  - stage: Deploy to Rinkeby
    if: branch = develop
    script: skip
  - script: ./scripts/migrate.sh rinkeby
  - stage: Publish to npm
    script: skip
    deploy:
      provider: npm
      email: razvan@centrifuge.io
      api_key:
        secure: Ohv0BrKWyasymh2HbOpMyU5yI2E3iofDM2fmn1C67A/R/ZvVEY22P6e3AysR+i9sBHx/ql/t3iiEcmbkBs7PsHuleILxqbOk1RPbdYuiUriEHFgKzS8f9bc11PjTRdz+n7K/P4+lrHl4FlTNWJ2fYWb5Wyw3EpSsAh8MeRqJI8mfPDspohdzXkJ/0TxjdLAY3RPXsGljd8Y5vygazvDMWRl9EKht7DMiXxWo6aNpWOqtvQO/6E4kiTyaSkyMl3VLgumBS2ouG2fFzVwdCFzaevjFD4K3j2B8qjjsB4jLf2GN3dMkOsmM0zdr2pqlUEEvBBBdsBdDzYN36H60b5MGIfgJ5G5OOAX4Avvn9jCBltZBBypQUKXDtCYGocLTHK6pLrkLMFV7chcYWsh1tJuWSWsUY77/Xs3uOuaCe3eBqWrIVCwu59oIN5YEQMTZjhugvJ0d6CqvIy+sQzZkT0rlOZvhRveMITwypM9xUDy7cXFDt02afhmjGGEpAUlCAJd10BAWyNceNX6juIpaG/9NNh2JCfQSUoYRnloWokPQheEn/tmI8bTIitbx1GuzkyXXQfmF6eA5k8LgRQ3rDt8faQWbeG8wo3qyOepH+21LRIU9qgMDHlztuPS2h3bEf888YsbpMRK5qGSfe/JV4dfBtVYParrgfNWAiiulJAfFtlk=
      on:
        repo: centrifuge/centrifuge-ethereum-contracts
        branch: develop