dist: trusty
sudo: required
group: beta
language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
env:
  secure: RymZPAUgaq7nxQsu4Cj0GmEyQ/KlLfvB8hoMzK94l+t+0yrUPe1bA/nGGCYD1KOJeG8mHbSg3QdQ+RC+xaV5TOGDSP2CNCUewgwrqVcWKsXzZFmqk1qEvwI5m30oY8C/0VQEg9KnxvDU7STvGFBh4hCRMWWib/GI0rnK3vbGognd+4AZGKCpzVwluGADnt9g125iWoljGoD26Gf9EaiGpGe1shUEPDnMe1vw69nD7TB/2lcFdyDH7wzeswKPmlv9LGxG9AFh11IuNkAtmtRUqSqrh72e1JHe+zB4/DQc34wiZcOp81J8bwFbtLGY63cfG6qBgt3im1dEpCnz7ZOyiNE+DkNI8QqsCfC/ic1yP0ka718oMcM4dpc/KgW9Nt88n98lCwwQMBdWhPtZdf2QnDtIb+S2SSS4WIRjjTA1VHWqlD7wzaLQvScJQV0wNoTlbkfFstzh1RF5BS7a/OMTIPZKGNOnYdtsDm2DgQmRBaYmJjYLsHaHYxpPWjX71VT7g7FsLH0x9DGkTjEKm8VyXR1HqU1XNka0wdqEkSPCHgkXBqHRKYlUiE+nwexyHeubopRhdButdIkjV9RHPiiRK7mIjLqXT6+KoCVRSk5Y410yZDe9xmus3cIkPgfh5PxsqkXTXjXilXXP75CQlk8JwFi3BRzAAU0thjgcz8tGYO8=
jobs:
  include:
  - stage: tests
    script:
    - npm run start-ganache &
    - npm run test
    deploy:
      provider: npm
      skip_cleanup: true
      email: razvan@centrifuge.io
      api_key:
        secure: sPrV2AIwTCf+FTDnRD/0//8052Kvb4XxCn6Rb6osjZPY5tNhmA+Y4lzatUmaIevD/3hHRAT8kiFqpUL17FrxjvjDQC7NQ2uakj1L25HN+4Wc9DadUCpkbn1+2lp3fF6fdOwkAwPr6sZyd1VUmnd849adjlQQikWNLRUM212t+OtQOWynCAYGR9egKn8EKqYrVrjpT2loYRc6z5GJlnSICwY28p30CdZgl+gYR/lw+VGOH2bfy2/BPA0egln0ZodJycGJrlG8xG3rNC8Z3/PcFCtEAIfRJulzJChDFbp+Tr9ME2NfjJR/lJ86R9la5EdJ4/ZLLAJXgwHA7Rh6VwpL9UPIThMZkNOKWgeCw7nWOQ2FS2uvp3BF1sOsWDjBUn9C8zctcSnW5UKe7+3na1u/XIEC5quJF2xjSkSWwmHtFhCVeMVC7ZpKCYZqreW10fw42oxqHplgjOdgwJhaoKxbDCY/h0qQMrR6hOk5bheI2XEm0KJei3gJJO8MrJvX2lTgxouKg7O7sHtVcTY5Olk9lkJJkR80v7rIGNq846csyU8jW+tY8ycUU5SxkWtAaPwyCU5c/9v15yfpNvdLzs8yA5i2ls5AJFTS/scUafnp6GerhLF03/xW1cpo2Y6lPvgBpuv6M8tY7uzKMkLNe1WA2c7hfmyNKtibBIkgPXvXZ0M=
      on:
        repo: centrifuge/centrifuge-ethereum-contracts
        branch: fix-travis-deploy

