dist: trusty
sudo: required
group: beta
language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
env:
  secure: RymZPAUgaq7nxQsu4Cj0GmEyQ/KlLfvB8hoMzK94l+t+0yrUPe1bA/nGGCYD1KOJeG8mHbSg3QdQ+RC+xaV5TOGDSP2CNCUewgwrqVcWKsXzZFmqk1qEvwI5m30oY8C/0VQEg9KnxvDU7STvGFBh4hCRMWWib/GI0rnK3vbGognd+4AZGKCpzVwluGADnt9g125iWoljGoD26Gf9EaiGpGe1shUEPDnMe1vw69nD7TB/2lcFdyDH7wzeswKPmlv9LGxG9AFh11IuNkAtmtRUqSqrh72e1JHe+zB4/DQc34wiZcOp81J8bwFbtLGY63cfG6qBgt3im1dEpCnz7ZOyiNE+DkNI8QqsCfC/ic1yP0ka718oMcM4dpc/KgW9Nt88n98lCwwQMBdWhPtZdf2QnDtIb+S2SSS4WIRjjTA1VHWqlD7wzaLQvScJQV0wNoTlbkfFstzh1RF5BS7a/OMTIPZKGNOnYdtsDm2DgQmRBaYmJjYLsHaHYxpPWjX71VT7g7FsLH0x9DGkTjEKm8VyXR1HqU1XNka0wdqEkSPCHgkXBqHRKYlUiE+nwexyHeubopRhdButdIkjV9RHPiiRK7mIjLqXT6+KoCVRSk5Y410yZDe9xmus3cIkPgfh5PxsqkXTXjXilXXP75CQlk8JwFi3BRzAAU0thjgcz8tGYO8=
jobs:
  include:
  - stage: tests
    script:
    - npm run start-ganache &
    - npm run test
  - stage: Deploy and publish
    script:
    - "./scripts/pullContracts.sh"
    - "./scripts/migrate.sh rinkeby"
    - "./scripts/migrate.sh kovan"
    deploy:
      provider: npm
      skip_cleanup: true
      email: razvan@centrifuge.io
      api_key:
        secure: VBz22KaWUN/t0BKO0omKBXSUQZPwTLj1u1UmlKF6K8LZzUHmgB/ZTPPyShgB5maQZnY712PI/CNaxc8ZZ6M6zKjImJgzckfLBawRdLzitp+QPtKQUXmhyQCmnxJzfuryYJynVYfQ3/WiiLkxXLCky/gi+rTBSqHuQ/y2JMbn2DVpthWTgvemh9W42rdVgNyYOVCDPaqQm5P6K0sUwr2DdUrXq/fP5IPG0RAsrSJRuVUf+bw0MLTDN+DgdmVT1s6BIBZJX2361wtMqouOHyWZh81OqLaF+PElHyQudWMBwUILuukz+AMZYH2fTjqLqvosArVTWoEj3xQ4oJQHHIiosNNYArKnaW8Wzm6d5rKNj0QGi+8efufCEnCPMtQ9KQGHNIoD/Z1NjoZWC4n2lTRK/UnM6PzNTIU/He1CWTW+OqeAxtb12+bTm4l0msk+IlhqeKVceKmRLwhXmbeI4PubPmYYwwIwS+NtGNsC6Bf098t8ED7CmGY1s74+dni5OjwPJfQu6DuuAZRtB7hGGWy+Q7El4+NjrYbfFFcxx98j4jieIkY4vwdoyKKYZd31uzhNLEJlz4Y75Dx/49jTwLnZMjTDARXdnVNOE7lLctkoJpS2s1HhKVtGvFiwy7PjUhOftXIIqvI2LYc5TZsI481yTHGrMB2cHemPFUQoMlY/qR0=
      on:
        repo: centrifuge/centrifuge-ethereum-contracts
        branch: fix-travis-deploy
