dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules

before_install:
  - npm install -g truffle, testrpc

before_script:
  - npm install
  - truffle version

script:
  - npm run testrpc-m &
  - truffle test
