dist: trusty
sudo: required
group: beta
language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
jobs:
  include:
  - stage: Unit tests
  - script: echo "Running unit tests (1)"
  - script: npm run start-ganache & test
  - stage: Deploy to Rinkeby
  - script: echo "Deploying to rinkeby (2)"
  - script: "./scripts/migrate.sh"
  - stage: Publish to npm
    deploy:
      provider: npm
      email: razvan@centrifuge.io
      api_key:
        secure: Ohv0BrKWyasymh2HbOpMyU5yI2E3iofDM2fmn1C67A/R/ZvVEY22P6e3AysR+i9sBHx/ql/t3iiEcmbkBs7PsHuleILxqbOk1RPbdYuiUriEHFgKzS8f9bc11PjTRdz+n7K/P4+lrHl4FlTNWJ2fYWb5Wyw3EpSsAh8MeRqJI8mfPDspohdzXkJ/0TxjdLAY3RPXsGljd8Y5vygazvDMWRl9EKht7DMiXxWo6aNpWOqtvQO/6E4kiTyaSkyMl3VLgumBS2ouG2fFzVwdCFzaevjFD4K3j2B8qjjsB4jLf2GN3dMkOsmM0zdr2pqlUEEvBBBdsBdDzYN36H60b5MGIfgJ5G5OOAX4Avvn9jCBltZBBypQUKXDtCYGocLTHK6pLrkLMFV7chcYWsh1tJuWSWsUY77/Xs3uOuaCe3eBqWrIVCwu59oIN5YEQMTZjhugvJ0d6CqvIy+sQzZkT0rlOZvhRveMITwypM9xUDy7cXFDt02afhmjGGEpAUlCAJd10BAWyNceNX6juIpaG/9NNh2JCfQSUoYRnloWokPQheEn/tmI8bTIitbx1GuzkyXXQfmF6eA5k8LgRQ3rDt8faQWbeG8wo3qyOepH+21LRIU9qgMDHlztuPS2h3bEf888YsbpMRK5qGSfe/JV4dfBtVYParrgfNWAiiulJAfFtlk=
      on:
        repo: centrifuge/centrifuge-ethereum-contracts
        branch: travis
env:
  migrate_address:
    secure: ipy/9dF6WzRec7wYNZla/Jhi4gnBhYCyRTxFwfyHUxhw2uw4vvvqbO/tOmq7BmU+l1LRZ+hrzSg4Biv9Xl01OHN1SfQftCsJCFKX91rT8r8CGpQo2+4EyWeYfwpNjA2j/pS28owL2Lq3Dv9n0/+NP+exAL5kxSBOI2md+VgKh+7yA+V//dsl5LF4KgXGcfrzG4quxuOZyStivadid808FMDqH1RepXMRuENptccAkwGUvNl/sh5PPlOGcnRYV4gfYbvwx2iwSTCU5xUOv26beRkt8Usd8AA+QL4FcZWFBaIcRmwazxjtqfWfTBG4UzY3jtOi07HRZm6Qrr7nZoxRnUnxHbioJg279KbONjj52Nu+70tIgjwhbD5EscuCxTRJoCsozOu/drbu7kzWkAv1+HDR0S/wIcpUm/l9ZCAAHaPyfnZSgb4AxgKHrW1MlFzc0jaOpbOwtWI0/weBWK5Njj+TbDNX0emV7B5RTOPezR4bQJzZ56kwpfYJSUZONwdvuyd5xWOGxkSY7IDZwoBAzv1HjmZwDz7A5dd+m7eAAVkXcRGLHuPSuyvQGFtQbrPQCBcnCdDiopzzXgx/LXJc/fB701IeRmd8YqPO/obsYmeBnySTYLmCJhWpVPeeYYGfsuAq4E11j4Zto/Dn1VgHM8FKxh6z052WTzlxiwpidZU=
  eth_key:
    secure: OWfA7m2pA1g7VAVz7ptOTycJ27K0vDgSRGdKfM3sno7c7p7GpP5sG2QHXHdEv0MkAuqMEyG/aWAEkoOvFfnEKHcutGNuvX4UnI+Uxuvao5fRf4A77YRZeKo2sPEjMUWG2gAyj/lkQOh6aChjv47KRaTrJXWhr5DLe7VVW006G7M37H9eMdBk3JhvRi26oqt8NPmwHgJ8CtM90IJhcZnVvcadTuWXijHPiQIlGpquX6qrNPIlMwLu0aF3/evDBVnIoClZ3tBsLUxSS7LM9h8UtiUjYvbYtIdZwsJloiBu6YMW6KhRJFSPwib9a0oS1fYuHK7F/542fzOVkVCTeOKUEDDjG4cohEq6l/6lKbUljM/TYIiRg/5hCPB+2vDUlqBwW6h8I93oNtXtODani6tUUvRHvvAORDyV5kqJULWRiQIHedW1hr2HjlM0CbhleTwIGV8/9X31Epo966Tu0wK0zw4yJZ9NjcAG8ZdYo5Awu7soltW4o0trjVHz5LM+VUVFsZ/lsFkcnSoOhFIlwbByG3aSZStSlP93rNX2J1tbOr/GOwiVfPYq2lfRv8iv6ID8O6XC4Mh1RkghfQD6w+8O30w4fVZ+3lPEMWINXu985RRfrVb9GgBRoDYI+xhWS2SV2EPthLwFw2/7dogNP4mZba/0MsexwtX5+9Z4RLM1GlA=
  rinkeby_provider:
    secure: rXiCEw13ZxT0+2lkL3DFZMs2dXoonOTevwPnL3gcVYCRtv2Pfkk+o1GLk7xnnVpwyyFMRotQArWR4cN+Tc0v4YvE79rfbJf9AxsMttjgqUaNgIGzV4zcQLBRuBcZVApgyJLmuzk3HpPktHOnac+RDfWHKmivRnoWg/2C+L/jI8xRRt4d2EBvUZRJgQZpHju7BdI5+LZrcRNWDc3kJagK8ZGOM9L6s/4iePS5P6vxg40wxHSO3Tlqu4KlvEy7kD8IkXden/0c44dZLaawMFbKOd7DTrUz9Yf4fI/UPIXNSTZ8QMtubym3/3OlgOWkJX9FOwre86aMiSFAKFhUfnhp3TmRfqHp8OeW7QjJnx5/PBIwM/yQl5/wYPpG26TP7CjxHUH03j+E8jGoAhWNcNn/p5FNfaomcv9iN9EaSP2xoY4sH4lkOblBOk5dTfGK0eB0bADdF3hSa89ieBawxcOyvhWAz9yPoxH7QgJG9g/gt/ZKgQ7SJYNVNZSgYhw/zulzE8UzFFMyVHACwEP4gmFrS1rGv566sPHJSrYT0TouIevxtfrVmSEwjfJl3JkP3IJCdle2+CA3CGmV8SvlFWPoQtLQgX8tFyilpR/xfEEpaFBWhi2h1BSRUHdtWy+zuHvgjJaHVXuMkL/wlrIw+W/SY9iUqOIgjl5sj5gSYlsn5Po=
