dist: trusty
sudo: required
group: beta
language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
env:
  secure: RymZPAUgaq7nxQsu4Cj0GmEyQ/KlLfvB8hoMzK94l+t+0yrUPe1bA/nGGCYD1KOJeG8mHbSg3QdQ+RC+xaV5TOGDSP2CNCUewgwrqVcWKsXzZFmqk1qEvwI5m30oY8C/0VQEg9KnxvDU7STvGFBh4hCRMWWib/GI0rnK3vbGognd+4AZGKCpzVwluGADnt9g125iWoljGoD26Gf9EaiGpGe1shUEPDnMe1vw69nD7TB/2lcFdyDH7wzeswKPmlv9LGxG9AFh11IuNkAtmtRUqSqrh72e1JHe+zB4/DQc34wiZcOp81J8bwFbtLGY63cfG6qBgt3im1dEpCnz7ZOyiNE+DkNI8QqsCfC/ic1yP0ka718oMcM4dpc/KgW9Nt88n98lCwwQMBdWhPtZdf2QnDtIb+S2SSS4WIRjjTA1VHWqlD7wzaLQvScJQV0wNoTlbkfFstzh1RF5BS7a/OMTIPZKGNOnYdtsDm2DgQmRBaYmJjYLsHaHYxpPWjX71VT7g7FsLH0x9DGkTjEKm8VyXR1HqU1XNka0wdqEkSPCHgkXBqHRKYlUiE+nwexyHeubopRhdButdIkjV9RHPiiRK7mIjLqXT6+KoCVRSk5Y410yZDe9xmus3cIkPgfh5PxsqkXTXjXilXXP75CQlk8JwFi3BRzAAU0thjgcz8tGYO8=
jobs:
  include:
  - stage: tests
    script:
    - npm run start-ganache &
    - npm run test
  - stage: Deploy and publish
    script:
    - "./scripts/pullContracts.sh"
    - "./scripts/migrate.sh rinkeby"
    - "./scripts/migrate.sh kovan"
    deploy:
      provider: npm
      skip_cleanup: true
      email: razvan@centrifuge.io
      api_key:
        secure: rnN0TNb1F3oz4X1KLn0EDH1+Jd8FS8jJ+5FouZWxuvY9BznNPl5ErCT66ini3GmFVIx1V3u9B66jUxkkBtYmyUV/JqQzQkBCA+oKo0Roog4eHquDWeBQZ0XgzVlSMPntYoGAAiqaltVErxznBM9vmMUphwQzxV5CX7YxrCB7p8kd2FuyTn50+0Y/i2rif9ItKun4t/4TGXD+DTtklj010ioIEcn3WPTOiN4inVZ14MoCrBKBjLuu7XVgictekrPpc+eRnlPgBAHMcgZaLjSd91xlkLEbZsA8d9SxlLKL0CDUyeHgQYPvfXxGNEh81gzUTdNKeJMygIP39QDBzLB5n5NF0g5M6hmcjzjMJWOeJeW40PhEPKQEcI8Q3997Qn/NVP66B0BYjBdHCgWCvVbRKr4GYebI9D0k3rwdgwUuGxl4gWMqfZscHH9uCCh1qoBooJiX1PznqW6wC9Rqvx607X2JdF7rkXQOVf9YrOW6QEwHBGNcf93XMxDXtukbBXTScM5uu6HJZ7w+BaSUOH1f8/KdjlcV8XEgfTK/o5n5fL3KbXZwQgeEs/8sy8IP9jyHBa6yw4YpgAYJmskP6bh930huBzQ8JaL/kICKGPaOYIxPGyEIi8Zhn1ZAUNV27rlJ1YrStMLMN+MLG0LUkjkhDXxIpNYquKUFbS6FoTS31Sk=
      on:
        repo: centrifuge/centrifuge-ethereum-contracts
        branch: fix-travis-deploy

